Topic api v2
ecolabdata/ecospheres-front pull request #154
Opened 2023-11-09 11:03 UTC by abulte

This introduces usage of data.gouv.fr's API v2, [especially the new topic's one](https://github.com/opendatateam/udata/pull/2913).

- Fetch topic list via APIv2 and use the `tag` filter
- Deal with new response format from v2
  - Datasets from Topic need to be fetched via HATEOAS
  - Resources from Dataset need to be fetched via HATEOAS

This is the minimum viable implementation I can think of. We could migrate more stuff to v2, especially datasets, but ATM we use it only when we need and use both v1 and v2.

I did not look into Topic write operations since they're not available on frontend anymore (when I started this morning, might have changed since then).

2023-11-09 15:32 UTC, streino reviewed
Yay ! La page bouquet est nettement plus réactive avec cette PR :)

J'approve pas encore, je préférerais qu'on traite cette histoire de formateur avant (cf mon comment à ce sujet) si possible.

2023-11-09 15:32 UTC, streino commented on src/store/TopicStore.js
> +      let response = await topicsAPIv2._list({
Je trouve quand même ça bien cradoc de hard coder les params type `page_size` dans les appels. Ça n'aurait pas plus sa place en constante dans le wrapper API voire dans la conf ?

2023-11-09 15:32 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +      loader.hide()
Bouger le `hide` en `finally` ?

2023-11-09 15:32 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
J'y comprends plus rien à ce formateur. Quelle version est la bonne ?
Si les deux résultent de son application, va falloir trouver comment obtenir un comportement déterministe...

Dans l'idéal, on fait une PR de format pour régler tous les soucis de formateur une bonne fois pour toute et on rebase cette PR dessus pour éviter de polluer la review (cf le gros changeset dans les vues qui n'a rien à voir avec l'API v2).

Ping @YeLnatSs

2023-11-09 15:34 UTC, abulte commented on src/store/TopicStore.js
> +      let response = await topicsAPIv2._list({
conf en effet, j'ai déjà `organizations_list_page_size`

2023-11-09 15:35 UTC, abulte commented on src/store/TopicStore.js
> +      let response = await topicsAPIv2._list({
après le store reste le bon endroit pour l'injecter je pense

2023-11-09 15:35 UTC, abulte commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
>  Quelle version est la bonne ?

Beats me 😅

2023-11-09 15:38 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
Oui je pense qu'il faut régler le problème du npm run format avant les prochaines PR.
Pour ce code suivant la logique du run format le return sur 2 lignes correspond au formattage

2023-11-09 15:59 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
@abulte Tu as bien run le formater de ton côté aussi ?
Pour info, si je `npm run format` sur [HEAD](https://github.com/ecolabdata/ecospheres-front/pull/154/commits/a03e4c308d4a75135cfcc2aea4763a7e2a909715), j'ai aucun diff. Donc j'ai moi aussi la version sur 1 ligne et pas 2.
@YeLnatSs tu peux tester la même opération ?

2023-11-09 15:59 UTC, abulte commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
Oui c'est le run format qui a fait la modification chez moi, pas touché à ça sinon.

2023-11-09 16:04 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +  return datasetsProperties.value[datasetsPropertiesKey].length
@streino Là, je l'ai sur 1 ligne avec le run format

2023-11-09 16:06 UTC, streino commented
> J'approve pas encore, je préférerais qu'on traite cette histoire de formateur avant (cf mon comment à ce sujet) si possible @YeLnatSs

En fait on a déjà la PR de format : https://github.com/ecolabdata/ecospheres-front/pull/155/
Reste à régler le [problème d'incohérence](https://github.com/ecolabdata/ecospheres-front/pull/154#discussion_r1388159536) constaté entre les runs par @abulte et @YeLnatSs.

2023-11-10 12:14 UTC, abulte commented
We have some dead code ATM, starting here https://github.com/ecolabdata/ecospheres-front/pull/154/files#diff-a33975f7574f38a410b90f6c4a06255593ee8506f7f9a7bf1106d96b15cf292cR42

Might change with #158.

Also, dead code continues : we can't go to a dataset detail page from the bouquet anymore, thus modifications made here to `DatasetDetailView` are moot (going directly to the dataset page will use the v1 payload).

2023-11-19 15:45 UTC, bonjourmauko requested changes
Peux-tu rajouter des tests au moins de l'API ? Il y a déjà un example du "DELETE /topics". (Il y a aussi un RFC pour des tests components/composable ici https://github.com/ecolabdata/ecospheres-front/pull/171).

2023-11-19 15:45 UTC, bonjourmauko commented on configs/ecospheres/config.yaml
> +  pagination_sizes:
```suggestion
  pagination_size:
```

2023-11-19 15:45 UTC, bonjourmauko commented on src/services/api/DatagouvfrAPI.js
> +  constructor(params) {
```suggestion
    constructor(args = {}) {
        const { baseUrl, version, endpoint, httpClient } = args
        this.baseUrl = baseUrl ?? this.baseUrl;
        this.version = version ?? this.version;
        this.endpoint = endpoint ?? this.endpoint;
        this.httpClient = httpClient ?? this.httpClient;
    }
```

2023-11-19 15:45 UTC, bonjourmauko commented on src/services/api/DatagouvfrAPI.js
> +  async list(params = {}) {
Quelles sont les paramètres possibles ?

2023-11-21 07:13 UTC, abulte commented on configs/ecospheres/config.yaml
> +  pagination_sizes:
Il y en plusieurs. Cf `organizations` dans le même fichier.

2023-11-21 07:13 UTC, abulte commented on src/services/api/DatagouvfrAPI.js
> +  async list(params = {}) {
Any, a lot. Ca construit une query string. Je vais changer le nom de la variable pour que ce soit plus clair.

2023-11-21 07:51 UTC, streino commented
> We have some dead code ATM, starting here https://github.com/ecolabdata/ecospheres-front/pull/154/files#diff-a33975f7574f38a410b90f6c4a06255593ee8506f7f9a7bf1106d96b15cf292cR42
> 
> Might change with #158.
> 
> Also, dead code continues : we can't go to a dataset detail page from the bouquet anymore, thus modifications made here to `DatasetDetailView` are moot (going directly to the dataset page will use the v1 payload).

#158 est mergé. On en est où du dead code ? cc @YeLnatSs

2023-11-21 07:55 UTC, abulte commented
@streino still dead :-)

2023-11-21 08:37 UTC, streino approved these changes
LGTM! Le loading est vraiment nettement plus rapide lorsqu'on a des gros topics :)

> @streino still dead :-)

Pas lié à cette PR donc pas bloquant ici, mais à traiter rapidement @YeLnatSs 🙏

2023-11-22 09:49 UTC, bonjourmauko approved these changes
Top !

2023-11-22 10:31 UTC, merged