Redesign Step 3
ecolabdata/ecospheres-front pull request #161
Opened 2023-11-15 10:46 UTC by YeLnatSs

## _Feature proposal #87 and #160 
 Bug fix #148 and #158 

### Job story

Pour #87 
Je remplis "Objectif du bouquet",
Je clique sur "Enregistrer" (un bouton bleu),
Je suis redirigé vers le bouquet que je viens de créer,
Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
Et je renseigne la « thématique » du bouquet en choissisant « Produire »,
Quand je renseigne la « thématique », je choisis le « chantier » « Nucléaire »,
Maintenant, je peux rajouter un ou plusieurs cas d'utilisation des données,

Quand je rajoute le premier, je remplis dans l'ordre:
« Inducateurs thérmodynamiques » dans « Libellé de la donnée »,
« Données à jour de Méteo France pour les indicateurs sous-cités » dans « Raison d'utilisation dans ce bouquet »,
Je cherche « Indicateurs thermodynamiques », mais je ne le trouve pas,

Je cherche donc l'URL dans mes notes (dans mon ordinateur)
Mais je ne le trouve pas non plus parce que mon PC est en panne ce matin,
Et je ne remplis donc pas « Retrouver la donnée via »

Je clique en « Ajouter la donnée »,
Et j'ai un message d'information m'indiquant de faire un choix pour « Retrouver la donnée via ».

Je choisis donc « Je n'ai pas trouvé la donnée »,
je clique en « Ajouter la donnée »,
Et je peux voir qu'elle aparaisse sous « Composition du bouquet (1) »,
Avec le libellé, la raison en guise de description, un lien « Aidez-nous à trouver la donnée »,
Et avec une pastille m'indiquant que la donnée es une « donnée non-disponible ».

Pour #160 
Je renseigne "Titre du bouquet",
Je remplis "Objectif du bouquet",
Je clique sur "Enregistrer" (un bouton bleu),
Je suis redirigé vers le bouquet que je viens de créer,
Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
Et je renseigne la « thématique » du bouquet en choissisant « Produire »,
Quand je renseigne la « thématique », je choisis le « chantier » « Nucléaire »,
Maintenant, je peux rajouter un ou plusieurs cas d'utilisation des données,

Quand je rajoute le premier, je remplis dans l'ordre:
« Inducateurs thérmodynamiques » dans « Libellé de la donnée »,
« Données à jour de Méteo France pour les indicateurs sous-cités » dans « Raison d'utilisation dans ce bouquet »,
Je cherche « Indicateurs thermodynamiques », mais je ne le trouve pas,

Je cherche donc l'URL dans mes notes (dans mon ordinateur)
Mais je ne le trouve pas non plus parce que mon PC est en panne ce matin,
Et je ne remplis donc pas « Retrouver la donnée via »

Je clique en « Ajouter la donnée »,
Et j'ai un message d'information m'indiquant de faire un choix pour « Retrouver la donnée via ».

Je choisis donc « Je n'ai pas cherché la donnée »,
Je clique en « Ajouter la donnée »,
Et je peux voir qu'elle aparaisse sous « Composition du bouquet (1) »,
Avec le libellé, la raison en guise de description, un lien « Aidez-nous à trouver la donnée »,
Et avec une pastille m'indiquant que la donnée es une « donnée non manquante ».

### Problem encountered by users

Avec le composant dsfrAccordion il n'y a pas la possibilité de mettre le tag "donnée non disponible" ou "donnée non manquante" à proximité du titre.

### Proposal of how to solve the problem

J'ai placé le tag "donnée non disponible" ou "donnée non manquante" au dessus de la description de la donnée. Il est visible au déroulement de l'accordéon.

### What changes

<img width="1191" alt="Capture d’écran 2023-11-15 à 11 42 59" src="https://github.com/ecolabdata/ecospheres-front/assets/11522622/68b15d6f-152f-47ff-afd8-464547cf848c">

#### Breaking changes

Nouveau design de la step 3 avec les boutons radio pour choisir quel type de donnée ajouté.

<img width="540" alt="Capture d’écran 2023-11-15 à 11 43 56" src="https://github.com/ecolabdata/ecospheres-front/assets/11522622/f3185566-18ac-4b98-8f1e-cb775fd0fc71">

<img width="1374" alt="Capture d’écran 2023-11-15 à 11 44 48" src="https://github.com/ecolabdata/ecospheres-front/assets/11522622/b446dcb8-d6b4-4834-be38-e904235208aa">

2023-11-16 11:14 UTC, streino requested changes

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                  value="1"
On ne peut pas utiliser `availabilityEnum` ici directement ? Il serait préférable d'avoir des constantes nommées plutôt que 1,2,3,4.

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +        selectedOption.value === '4'
js n'a pas de `switch` ?

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'Donnée non manquante'
Donnée _non_ manquante ?

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                    href="mailto:ecospheres@developpement-durable.gouv.fr"
Config pour ce genre de truc

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'DONNÉE NON DISPONIBLE'
Pourquoi uppercase ici ?

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +      <div v-show="currentStep === 4" class="step4">
Je n'ai pas regardé en détail mais il y a pas mal d'overlap entre le code du step 3 et 4, il n'y a pas moyen de factoriser ?

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                  v-if="datasetProperties.available !== 'available'"
Les labels type `available`, `missing`, etc devraient être des enum/constantes.

2023-11-16 11:14 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +    datasets: datasets.value.map((d) => d.dataset.id)
Sur ce genre de truc critique il faudrait qu'on ait des tests à terme

2023-11-16 12:17 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +          titre: libelle.value,
Yes, c'est bon pour le changement

2023-11-16 12:18 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +        selectedOption.value === '4'
oui , il y en a. J'étais parti sur du ternaire pour ne pas que ce soit long mais je peux mettre aussi en switch

2023-11-16 12:20 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'Donnée non manquante'
Texte présent dans la job story rédigée. Mais à confirmer avec Martin et toi quel texte est préférable
(Donnée non recherché, Donnée manquante, ...)

2023-11-16 12:21 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'DONNÉE NON DISPONIBLE'
C'est ma faute. J'ai modifié.
Pas encore remis en forme avec le availabilityEnum

2023-11-16 12:32 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                    href="mailto:ecospheres@developpement-durable.gouv.fr"
C'est changé

2023-11-16 15:00 UTC, streino commented on configs/ecospheres/config.yaml
> +mail: ecospheres@developpement-durable.gouv.fr
Migrer dans la section `website` et renommer `contact_email`

2023-11-16 15:06 UTC, streino commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'Donnée non manquante'
C'est bien "donnée manquante" et non "donnée non manquante"

2023-11-16 15:49 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                      ? 'Donnée non manquante'
Changement fait

2023-11-16 15:53 UTC, YeLnatSs commented on configs/ecospheres/config.yaml
> +mail: ecospheres@developpement-durable.gouv.fr
c'est bon pour le changement

2023-11-16 16:01 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +        selectedOption.value === '4'
J'ai changé en switch

2023-11-16 17:10 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                  v-if="datasetProperties.available !== 'available'"
J'ai fait le changement

2023-11-16 18:00 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +    datasets: datasets.value.map((d) => d.dataset.id)
Je confirme que ça aurait pu être géré avec un test. Erreur de ma part

2023-11-17 09:47 UTC, edelagnier commented on src/views/bouquets/BouquetEditView.vue
> +        case '4':
Pour la lisibilité future je pense qu'il vaudrait mieux éviter d'utiliser des valeurs neutres (1,2,3,4) pour la valeur des options. Idéalement si les values des options peuvent directement être celles de l'énum tu n'auras meme pas besoin de faire le switch case

2023-11-17 09:47 UTC, edelagnier commented on src/views/bouquets/BouquetEditView.vue
> +        description: description.value,
+1 pour l'anglais coté nom des variables

2023-11-17 09:47 UTC, edelagnier commented on src/views/bouquets/BouquetEditView.vue
> +  if (newValue === '1') {
idem, ici il serait pratique d'avoir l'énum plutot que des chiffres pour comprendre pourquoi on mets les autres valeurs à jour. Dans la même veine, le selectedOption est très neutre, est ce que tu aurais une idée de nom plus explicite ? DatasetRetrievalOption ? ou ce qui te semble le plus pertinent pour décrire la variable

2023-11-17 09:47 UTC, edelagnier commented on src/views/bouquets/BouquetEditView.vue
> +      <div v-show="currentStep === 4" class="step4">
Effectivement, pour la factorisation il faudra juste mettre en place le découpage pour pouvoir réutiliser des composants facilement à travers le formulaire. On essaiera de l'inclure en fin de POC https://github.com/ecolabdata/ecospheres-front/pull/145

2023-11-17 10:24 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +        case '4':
J'ai fait le changement avec les enums

2023-11-17 10:24 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +                  value="1"
J'ai fait le changement avec les enums

2023-11-17 10:25 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +        description: description.value,
Oui j'avais fait le changement en anglais 'title' et 'description'

2023-11-17 10:28 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +  if (newValue === '1') {
C'est bon aussi. J'ai gardé le nom DatasetRetrievalOption

2023-11-17 10:29 UTC, YeLnatSs commented on src/views/bouquets/BouquetEditView.vue
> +      <div v-show="currentStep === 4" class="step4">
Pour celui-là il sera traité dans une autre modif => https://github.com/ecolabdata/ecospheres-front/pull/161#discussion_r1397000190

2023-11-17 19:33 UTC, bonjourmauko approved these changes

2023-11-17 20:13 UTC, bonjourmauko approved these changes

2023-11-17 20:14 UTC, merged