feat: parametrize site name
ecolabdata/ecospheres-front pull request #163
Opened 2023-11-16 12:38 UTC by geoffreyaldebert

## Ce que fait la PR

- Met en variable le nom du site
- ajoute une marianne dans le favicon.ico

## Usage

Utile pour gérer les différents noms des plateformes dont ce code source sera la base (ecospheres, meteo.data.gouv.fr ...)

2023-11-16 13:24 UTC, abulte reviewed
Je l'aurais mis dans la config yaml des sites. Mais peut-être que c'est galère à injecter dans la config vite ?

2023-11-19 15:50 UTC, bonjourmauko requested changes
Mettre la config dans config.yaml pour garder une cohérence avec le reste/

2023-11-22 13:55 UTC, abulte commented
We might be able to handle the config injection differently since we're now loading it in the vite config, but it should be good enough for this PR.

2023-11-23 08:25 UTC, bonjourmauko approved these changes

2023-11-23 08:26 UTC, merged