Ec 112 visualizing created bouquet
ecolabdata/ecospheres-front pull request #176
Opened 2023-11-22 15:58 UTC by YeLnatSs

Relates to #112 

Visualisation de la page du bouquet

Après avoir rempli le formulaire de création de bouquet ou après avoir chercher un bouquet, j'accède à la page du bouquet avec les informations liés: thème, chantier, titre, description, jeux de données(si existant et trouvé)

Il y a la possibilité de créer un nouveau bouquet ou de copier l'url de la page

![screencapture-localhost-5173-bouquets-nourriture-2023-11-22-16_44_32](https://github.com/ecolabdata/ecospheres-front/assets/11522622/22a5c28a-765d-4118-bb44-966ddc0753ed)

2023-11-22 16:48 UTC, streino requested changes

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +          to: `/?theme=${theme.value}`
Renvoyer sur `/bouquets/?theme` comme pour https://github.com/ecolabdata/ecospheres-front/pull/168/files#diff-97bb20b14629cd18b7404ba1fdb458a27c845a5a448fb3265a8b017cdd7751d2R69

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
Je m'en remets à vous @YeLnatSs @edelagnier pour la partie html/css 🙏

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
@martyKN je suis pas convaincu de l'utilité du bouton "Copier l'url de la page" en bas de page : 

https://deploy-preview-176--ecospheres.netlify.app/bouquets/nourriture
<img src="https://github.com/ecolabdata/ecospheres-front/assets/30210525/fada1f61-e22a-49d3-8320-0354e9e207bd" width="500"/>

Il sera plus facile de l'ajouter par la suite si on trouve que ça manque que de le retirer. Par exemple dans une passe de polish où on ajoutera ce genre de bouton d'un coup sur toutes les pages qui peuvent en bénéficier.

Cela dit, c'est le design qui a le dernier mot là dessus :)

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +          :label="subtheme"
https://deploy-preview-176--ecospheres.netlify.app/bouquets/nourriture
<img src="https://github.com/ecolabdata/ecospheres-front/assets/30210525/73842410-b8fe-4ef3-8b8d-40f5300711e4" width="500"/>

@martyKN Questions/comments :
1. Le tag du chantier à côté du titre du bouquet est-il pertinent sachant qu'on a le breadcrumb avec cette info au dessus ?
2. Le lien "Revenir aux résultats" est-il aussi prévu pour les fiches jeux de données ? Si oui, je pense qu'il faut qu'on le case dans la release.
3. Perso j'aurais inversé le breadcrumb et le lien "Revenir aux résultats".

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +                  :href="datasetProperties.uri"
Même traitement que https://github.com/ecolabdata/ecospheres-front/pull/173/commits/7e894b77e8149bd2e5bf8d591677554900b3c148#diff-c04768bad73de0860e75fee641e128c9ba6d5d8f37dbf2b8554f38dfd68fdc56R130

2023-11-22 16:48 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
>              <DsfrAccordion
Ça pourrait être pratique d'avoir un bouton expand/collapse all, pour déplier/replier l'ensemble des jeux de données d'un bouquet. Pour l'instant il faut le faire manuellement pour chaque JDD en allant cliquer sur leur titre.

@martyKN t'en penses quoi ?
@YeLnatSs ça serait simple à ajouter ?

2023-11-22 17:44 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
>              <DsfrAccordion
Si c'est compliqué on verra plus tard

2023-11-23 08:10 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +                  :href="datasetProperties.uri"
Celui-ci est fixé via la PR https://github.com/ecolabdata/ecospheres-front/pull/173

2023-11-23 08:13 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +          to: `/?theme=${theme.value}`
C'est modifié

2023-11-23 08:35 UTC, martyKN commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
ce bouton est la pour une raison de mesure d'impact. En mettant ce bouton, je me suis dit qu'on pouvait alors tracker les click sur ce bouton et avoir un indicateur d'usage/vanité sur le partage du bouquet. Voila (sa seule) utilité. tu en dis quoi? on enlève? on garde?

2023-11-23 08:36 UTC, martyKN commented on src/views/bouquets/BouquetDetailView.vue
> +          :label="subtheme"
breadcrumb au dessus de "revenir aux resultats" et je suis d'avis qu'on garde le tag ==> beaucoup plus lisible/visuel que le breadcrumb

2023-11-23 08:37 UTC, martyKN commented on src/views/bouquets/BouquetDetailView.vue
>              <DsfrAccordion
si possible et facile go sinon no go

2023-11-23 08:48 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +          :label="subtheme"
ok je fais le changement de position

2023-11-23 09:01 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +          :label="subtheme"
modification faite

2023-11-23 09:28 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
Vous pouvez laisser et faire des tests. S'il est cliqué par l'utilisateur ou pas en fonction des résultats sur le nommbre de click vous pourrez juger si vous le supprimer ou pas.  @streino @martyKN

2023-11-23 10:26 UTC, bonjourmauko commented on src/views/bouquets/BouquetDetailView.vue
>              <DsfrAccordion
AMHA ce type de changement devraient être faits avec de feature flags et les tester auprès des utilisateurs d'abord. Là comme ça, la seule variable qu'on a est si c'est simple ou pas à faire. Du coup +1 pour plus tard.

2023-11-23 12:04 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
Ok, j'avais zappé. Je suis pas convaincu dans la mesure où c'est super partiel comme info (quel ratio clic bouton vs copie de l'URL dans la barre du navigateur peut-on espérer ?). M'est avis aussi qu'il faut qu'on pense ça de manière systématique sur tout le site, et pour on sera déjà contents de sortir quelque chose et d'avoir des pageviews ;)

Mais on peut aussi décider de mettre ce bouton en test ici seulement et voir si on récupère qqch d'exploitable.

Comme tu le sens @martyKN

2023-11-23 12:08 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
> +                  :href="datasetProperties.uri"
My bad, je croyais qu'il fallait le changer ici aussi

2023-11-23 13:53 UTC, streino commented on src/views/bouquets/BouquetDetailView.vue
>              <DsfrAccordion
Je ferme cette conversation, on verra plus tard

2023-11-23 14:40 UTC, bonjourmauko commented
@YeLnatSs j'ai rajouté ceci dans la description de l'issue #112 :

> Quand il s'agit d'une donnée d'écosphères, je clique sur « Accéder au catalogue » et je vois ceci :
>
> ![Visualiser un dataset (métadonnées)](https://github.com/ecolabdata/ecospheres-front/assets/329236/bef4f68a-004c-42de-b8dc-3077b753da96)

Peut-on le faire ici ? (cela correspondait au début au ticket #146).

2023-11-24 08:22 UTC, YeLnatSs commented
> @YeLnatSs j'ai rajouté ceci dans la description de l'issue #112 :
> 
> > Quand il s'agit d'une donnée d'écosphères, je clique sur « Accéder au catalogue » et je vois ceci :
> > ![Visualiser un dataset (métadonnées)](https://user-images.githubusercontent.com/329236/285173430-bef4f68a-004c-42de-b8dc-3077b753da96.png)
> 
> Peut-on le faire ici ? (cela correspondait au début au ticket #146).

@streino ça correspond à ton retour sur la PR recap non ?
au click sur "Accéder au catalogue" d'une donnée écosphère ?

2023-11-24 09:33 UTC, edelagnier commented
Il y aurait un bout de css à changer pour les tags "aménagements des villes". Contrairement à d'autre tag, la couleur est trop sombre pour que le texte gris soit lisible 

![image](https://github.com/ecolabdata/ecospheres-front/assets/20337428/af4a1133-6720-45ba-a827-76f4526ce1e8)

2023-11-24 09:44 UTC, martyKN commented
clairement c'est illisible comme ca. Faudrait soit passer le texte en blanc soit changer la couleur de fond. 
Pour commencer on passe le texte en blanc, on verra après si ca va en terme d'harmonie avec les autres tag

2023-11-24 10:02 UTC, YeLnatSs commented
> clairement c'est illisible comme ca. Faudrait soit passer le texte en blanc sur ce tag soit changer la couleur de fond. Pour commencer on passe le texte en blanc, on verra après si ca va en terme d'harmonie avec les autres tag qui ont un texte en gris

J'ai fait le changement pour le texte blanc sur ce tag

2023-11-24 10:03 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +    <DsfrButton
je ferme cette discussion

2023-11-24 10:10 UTC, edelagnier commented on src/views/bouquets/BouquetDetailView.vue
> +    ? `#${parseInt(theme.textColor, 16).toString(16).padStart(6, '0')}`
peut etre extraire la fonction de calcul ?

2023-11-24 10:16 UTC, YeLnatSs commented on src/views/bouquets/BouquetDetailView.vue
> +    ? `#${parseInt(theme.textColor, 16).toString(16).padStart(6, '0')}`
c'est bon tu peux checker

2023-11-24 14:02 UTC, streino commented
Certains des bouquets ne s'affichent pas avec l'accordéon de la liste des jeux de données ouvert. 
Je sais pas si c'est reproductible. Au cas où :
- Expanded : https://deploy-preview-176--ecospheres.netlify.app/bouquets/pollution-de-leau
- Collapsed : https://deploy-preview-176--ecospheres.netlify.app/bouquets/prevenir-les-ilots-de-chaleur-urbains, https://deploy-preview-176--ecospheres.netlify.app/bouquets/demolition

2023-11-24 14:06 UTC, edelagnier commented
Je viens de regarder, pour moi le premier lien affiche des accordéons ouverts, le second des accordéons fermés.
Le comportement souhaité est que tout soit ouvert ? Je peux y jeter un oeil entre deux étapes de la décomposition

2023-11-24 14:16 UTC, streino commented
> Je viens de regarder, pour moi le premier lien affiche des accordéons ouverts, le second des accordéons fermés. Le comportement souhaité est que tout soit ouvert ? Je peux y jeter un oeil entre deux étapes de la décomposition

Oui on avait décidé tout ouvert. Mais surtout que tous les bouquets se comportent pareil.

2023-11-24 14:48 UTC, bonjourmauko commented
@edelagnier il n'y a pas encore de bouquets en production, et il est même prévu de tout nettoyer #159 . Du coup, ma proposition, au lieu de faire cela marcher avec les bouquets anciens, serait  juste d'écrire les interfaces avec lesquelles cette foncionnalité fonctionne. @streino avait déjà proposé de commencer à stabiliser le schema de données, on pourrait profiter de manière opportuniste cette issue pour faire avancer de chantier.

2023-11-24 15:21 UTC, streino commented
En effet pas besoin de s'embêter avec les anciens bouquets, ils vont bientôt disparaître.
LGTM sur cette PR. @edelagnier si/quand tu es ok aussi, tu peux merger 🙏

2023-11-28 12:57 UTC, bonjourmauko approved these changes

2023-11-29 08:46 UTC, merged