Feat/pagination ressources
ecolabdata/ecospheres-front pull request #211
Opened 2023-12-05 10:15 UTC by Jorek57

Close https://github.com/ecolabdata/ecospheres-front/issues/208

Juste pour être sûr que les attendus sont là, il reste la nav à centrer et sans doute 2-3 points à corriger

2023-12-05 10:56 UTC, streino requested changes

2023-12-05 10:59 UTC, abulte commented on src/store/DatasetStore.js
> +    async fetchDatasetResources(datasetId, page, pageSize) {
Oui mieux dans un store 👍

2023-12-05 11:08 UTC, abulte commented on src/views/datasets/DatasetDetailView.vue
> +    let datas = await datasetStore.loadResources(
```suggestion
    const datas = await datasetStore.loadResources(
```

2023-12-05 11:08 UTC, abulte commented on src/views/datasets/DatasetDetailView.vue
> +    let datas = await datasetStore.loadResources(
Maybe `_resources` or `resourcesRes` for more meaningful naming

2023-12-05 11:08 UTC, abulte commented on src/store/DatasetStore.js
> +    async fetchDatasetResources(datasetId, page, pageSize) {
Ah attends on est déjà dans un store 😅 Du coup nitpick, ça peut rester là je pense, et le top c'est un store dédié mais vraiment pas obligé je pense.

2023-12-05 11:08 UTC, abulte commented on src/views/datasets/DatasetDetailView.vue
> +    totalResults.value = datas.total
Maybe use destructuring here

2023-12-05 12:33 UTC, streino commented on src/store/DatasetStore.js
> +    async fetchDatasetResources(datasetId, page, pageSize) {
On est dans un store mais il faut tout de même ajouter explicitement les ressources à `this.data`, ou bien j'ai raté un truc ?

2023-12-05 13:20 UTC, abulte commented on src/store/DatasetStore.js
> +    async fetchDatasetResources(datasetId, page, pageSize) {
(Pardon j'ai du mal avec le français technique, `cacher <> to hide` 😅 )

Dans l'idéal oui mais je ne l'avais pas fait là par exemple https://github.com/ecolabdata/ecospheres-front/pull/154/files#diff-844ed29f3b50730310cc133feaf0c79bba2c3356a80d5d8cecfc9441e28034dbR156

2023-12-05 13:33 UTC, streino commented on src/store/DatasetStore.js
> +    async fetchDatasetResources(datasetId, page, pageSize) {
Désolé pour le franglais :/
En effet le "problème" était déjà là, donc pas spécifique à la PR. Je me demande si c'est l'occas de le faire ou sinon on l'ajoutera plus tard.

2023-12-05 14:56 UTC, streino commented on src/views/datasets/DatasetDetailView.vue
> +const pageSize = ref(20)
Au passage, 20 c'est beaucoup d'un coup. data.gouv pagine à 6, on peut prendre la même valeur par défaut pour démarrer.

2023-12-05 18:09 UTC, streino requested changes

2023-12-05 18:09 UTC, streino commented on configs/meteo-france/config.yaml
> +  files_page_size: 6
Il y a déjà une section `pagination_sizes` juste en dessous => `pagination_sizes.resources_list`

2023-12-05 18:22 UTC, Jorek57 commented on configs/meteo-france/config.yaml
> +  files_page_size: 6
Merci, modifié dans le dernier commit

2023-12-05 18:28 UTC, streino approved these changes

2023-12-07 09:02 UTC, geoffreyaldebert approved these changes

2023-12-07 09:02 UTC, merged